####LOGIN
### REQUEST JWT TOKEN
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "client3",
  "password": "client"
}

##### Occurrences
GET http://localhost:8080/occurrences/api/occurrences
Accept: application/json

### Create Ocurrence
POST http://localhost:8080/occurrences/api/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyMjIzMDg1LCJleHAiOjE2NzIyMjY2ODV9.5_XkxLitzXAk96rhGK5J29p9nFurnbE9W9jeWlaEL_c
Content-Type: application/json

{
  "usernameClient": "client2",
  "date": "2021-07-20",
  "insuredAssetType": "VEHICLES",
  "state": "PENDING",
  "insuranceCode": "AL-123",
  "description": "ola"
}

###DOCUMENTS
POST http://localhost:8080/occurrences/api/documents/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyMTg3MjQ5LCJleHAiOjE2NzIxOTA4NDl9.jVq0fDRi63gNr7EBWB9TFa8WOmRcPRhJHZMZSOzfrck
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="<C:\popo\statistics.txt"

--boundary

###
GET http://localhost:8080/occurrences/api/documents/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyMjIxNjAwLCJleHAiOjE2NzIyMjUyMDB9.Q8UDYtmCHsLEcP6drMzcOUPUv_eHNmIof9coowL6S4s
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/occurrences/api/documents/2/exists HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyMTg3MjQ5LCJleHAiOjE2NzIxOTA4NDl9.jVq0fDRi63gNr7EBWB9TFa8WOmRcPRhJHZMZSOzfrck
Content-Type: application/x-www-form-urlencoded

##### CLIENT Occurrences
GET http://localhost:8080/occurrences/api/clients/client3/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyMjIzMDg1LCJleHAiOjE2NzIyMjY2ODV9.5_XkxLitzXAk96rhGK5J29p9nFurnbE9W9jeWlaEL_c
Accept: application/json

### Create Company
POST http://localhost:8080/occurrences/api/companies
Content-Type: application/json

{
  "username": "company1",
  "password": "123",
  "name": "Company 1",
  "email": "company@mail.pt",
  "address": "Rua 1",
  "phoneNumber": 987654321,
  "nipc": 123456
}

### Create Expert
POST http://localhost:8080/occurrences/api/experts
Content-Type: application/json

{
  "username": "expert1",
  "password": "123",
  "name": "Expert 1",
  "email": "expert@mail.pt",
  "company_username": "company1"
}

### GET Experts
GET http://localhost:8080/occurrences/api/experts
Accept: application/json

#### EXPERT FAILS OCCURRENCE
PATCH http://localhost:8080/occurrences/api/occurrences/1/expert1/disapprove
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyMjIzMDg1LCJleHAiOjE2NzIyMjY2ODV9.5_XkxLitzXAk96rhGK5J29p9nFurnbE9W9jeWlaEL_c
Content-Type: application/json

{
    "usernameExpert": "expert1",
    "description": "Expert 1 disapproved"
}
