###HAPPY PATH

### Login
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "repairer1",
  "password": "123"
}

### Login
POST http://localhost:8080/occurrences/api/auth/login/admin
Content-Type: application/json
Accept: application/json

{
  "username": "admin1",
  "password": "123"
}

### Create Ocurrence
POST http://localhost:8080/occurrences/api/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNjczMDQzODcwLCJleHAiOjE2NzMwNDc0NzB9.zI8_EthirXaeQcZRjnhdJRfYqlzfNiI0n0REvAy3is8
Content-Type: application/json

{
  "usernameClient": "client1",
  "entryDate": "10/1/2023",
  "state": "PENDING",
  "insuranceCode": "ALL-1298389",
  "coverageType": "ACCIDENTAL_DAMAGE",
  "description": "Iphone dropped in the toilet"
}

### Create Expert
POST http://localhost:8080/occurrences/api/experts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpYXQiOjE2NzMwNDU2NjYsImV4cCI6MTY3MzA0OTI2Nn0.webTm6wXu7RZeKlckMZ_DOrpFPapmXAZI4qRhQvStK8
Content-Type: application/json

{
  "username": "expert3",
  "password": "123",
  "name": "Expert 3",
  "email": "expert3@mail.pt",
  "company_username": "Allianz"
}

### Assign expert to occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert3/occurrences/2/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleHBlcnQxIiwiaWF0IjoxNjczMDQzOTYzLCJleHAiOjE2NzMwNDc1NjN9.r1acxhf59SXjGSTGoz0M3isWrQgLBPm0mSsQDxzDWPY
Content-Type: application/json

##### Get Occurrence Details
GET http://localhost:8080/occurrences/api/occurrences/2
Accept: application/json

### Expert Approve Occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert3/occurrences/2/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleHBlcnQxIiwiaWF0IjoxNjczMDQzOTYzLCJleHAiOjE2NzMwNDc1NjN9.r1acxhf59SXjGSTGoz0M3isWrQgLBPm0mSsQDxzDWPY
Content-Type: application/json

{
  "description": "The only damage seems to be with the screen. The phone is working fine"
}

### Client Adds Repairer to Occurrence
PATCH http://localhost:8080/occurrences/api/clients/client1/occurrences/1/repairers/repairer1/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzMwNDQ4MDcsImV4cCI6MTY3MzA0ODQwN30.Omk4HoqxuCLw7ayZ7A321r2VVoXZRb3NDemi7g8XAfs
Content-Type: application/json

### Expert Approves Repairer
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/2/acceptRepairer
Content-Type: application/json

### Repairer Starts Repair
PATCH http://localhost:8080/occurrences/api/repairers/repairer1/occurrences/2/start
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzMwNDQ4MDcsImV4cCI6MTY3MzA0ODQwN30.Omk4HoqxuCLw7ayZ7A321r2VVoXZRb3NDemi7g8XAfs
Content-Type: application/json

### Repairer Finishes the Repair
PATCH http://localhost:8080/occurrences/api/repairers/repairer1/occurrences/2/finish
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzMwNDQ4MDcsImV4cCI6MTY3MzA0ODQwN30.Omk4HoqxuCLw7ayZ7A321r2VVoXZRb3NDemi7g8XAfs
Content-Type: application/json

{
  "description": "Changed the Screen"
}

### SAD PATH
### Login
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "client1",
  "password": "123"
}

### Create Ocurrence
POST http://localhost:8080/occurrences/api/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyOTMzNDQ1LCJleHAiOjE2NzI5MzcwNDV9.nhKcDTIvRqZsAsFIlTjWuSr70ZLc8yc31YG8AUP3fPU
Content-Type: application/json

{
  "usernameClient": "client1",
  "entryDate": "10/1/2023",
  "state": "PENDING",
  "insuranceCode": "ALL-1298389",
  "coverageType": "WATER_DAMAGE",
  "description": "Iphone dropped in the toilet"
}

### Assign expert to occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/1/assign
Content-Type: application/json

### Expert Disapprove Occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert1/occurrences/1/disapprove
Content-Type: application/json

{
  "description": "Insurance does not cover this type of damage"
}
