####LOGIN
### REQUEST JWT TOKEN
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "repairer1",
  "password": "123"
}

##### Get Occurrences
GET http://localhost:8080/occurrences/api/occurrences
Accept: application/json

##### Get Occurrence Details
GET http://localhost:8080/occurrences/api/occurrences/1
Accept: application/json

### Create Ocurrence
POST http://localhost:8080/occurrences/api/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyOTMzNDQ1LCJleHAiOjE2NzI5MzcwNDV9.nhKcDTIvRqZsAsFIlTjWuSr70ZLc8yc31YG8AUP3fPU
Content-Type: application/json

{
  "usernameClient": "client1",
  "entryDate": "10/1/2023",
  "state": "PENDING",
  "insuranceCode": "ALL-1298389",
  "coverageType": "ACCIDENTAL_DAMAGE",
  "description": "ola"
}

### Update Ocurrence
PUT http://localhost:8080/occurrences/api/occurrences/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyODU1OTA0LCJleHAiOjE2NzI4NTk1MDR9.D1gCSQstEQ1JroH0p2CkdNx7PCTYWfiTN5LkBgSFJ1U
Content-Type: application/json

{
  "usernameClient": "client3",
  "entryDate": "10/1/2023",
  "state": "DISAPPROVED",
  "insuranceCode": "ALL-1298389",
  "description": "ola"
}

### Delete Ocurrence
DELETE http://localhost:8080/occurrences/api/occurrences/2
Content-Type: application/json

###DOCUMENTS
### Add Documents to occurrency
POST http://localhost:8080/occurrences/api/documents/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyOTEzNjE3LCJleHAiOjE2NzI5MTcyMTd9.um4469JI7SxLC_cdeIjUIemytQFz7dLnhkvj6z4uYFY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="<C:\popo\statistics.txt"

--boundary

### Gets documents of occurrency with id = 2
GET http://localhost:8080/occurrences/api/documents/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyOTEzNjE3LCJleHAiOjE2NzI5MTcyMTd9.um4469JI7SxLC_cdeIjUIemytQFz7dLnhkvj6z4uYFY
Content-Type: application/x-www-form-urlencoded

###Download documents with id=1
GET http://localhost:8080/occurrences/api/documents/download/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyNjY4NTQ0LCJleHAiOjE2NzI2NzIxNDR9.twJ6VmBx_BXRDNqdv-Jedc0zJOGwa9IFEwffiSFFe9M
Content-Type: application/x-www-form-urlencoded

###See if occurrency with id = 2 has documents
GET http://localhost:8080/occurrences/api/documents/2/exists HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyOTEzNjE3LCJleHAiOjE2NzI5MTcyMTd9.um4469JI7SxLC_cdeIjUIemytQFz7dLnhkvj6z4uYFY
Content-Type: application/x-www-form-urlencoded

##### CLIENT Occurrences
GET http://localhost:8080/occurrences/api/clients/client2/occurrences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyOTE5ODQ0LCJleHAiOjE2NzI5MjM0NDR9.gM59HTRpfwRboS8N-Dmc3CwFmXRQqd-gbxXmYBOYTfM
Accept: application/json

### Create Expert
POST http://localhost:8080/occurrences/api/experts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpYXQiOjE2NzI5MzI4NjAsImV4cCI6MTY3MjkzNjQ2MH0.JJ0dY59TH0yug6muh2DfZseYr-oW0PE2MFJF7gRjT4o
Content-Type: application/json

{
  "username": "expert2",
  "password": "123",
  "name": "Expert 3",
  "email": "expert3@mail.pt",
  "company_username": "Allianz"
}

### Create Repairer
POST http://localhost:8080/occurrences/api/repairers
Content-Type: application/json

{
  "username": "repairer1",
  "password": "123",
  "name": "Repairer 1",
  "email": "repairer@mail.pt",
  "address": "Rua 1"
}

### Update Expert
PUT http://localhost:8080/occurrences/api/experts/expert1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzMzNjMyMzUsImV4cCI6MTY3MzM2NjgzNH0.GHvy2leP4I5ml9tY0g2vJL8FR3tznGY4npmBFL47A4I
Content-Type: application/json

{
  "name": "Expert 3",
  "email": "expert3@mail.pt"
}

### Update Repairer
PUT http://localhost:8080/occurrences/api/repairers/repairer1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzMzNjMyMzUsImV4cCI6MTY3MzM2NjgzNH0.GHvy2leP4I5ml9tY0g2vJL8FR3tznGY4npmBFL47A4I
Content-Type: application/json

{
  "name": "Repairer 2",
  "email": "repairer2@mail.pt",
  "address": "Rua 1"
}

### Update Expert's Insurance Company
PATCH http://localhost:8080/occurrences/api/experts/expert1/insuranceCompany/Fidelidade
Content-Type: application/json

### GET Experts
GET http://localhost:8080/occurrences/api/experts
Accept: application/json

### GET specific Expert
GET http://localhost:8080/occurrences/api/experts/expert2
Accept: application/json

### Assign expert to occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/2/assign
Content-Type: application/json

### Unassign expert from occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/1/unassign
Content-Type: application/json

### Expert Disapprove Occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert1/occurrences/1/disapprove
Content-Type: application/json

{
    "description": "Occurrence disapproved, because..."
}

### Expert Approve Occurrence
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/2/approve
Content-Type: application/json

{
  "description": "The problem seems to be with..."
}

### Client assigns Repairer to Occurrence
PATCH http://localhost:8080/occurrences/api/clients/client1/occurrences/2/repairer1/assign
Content-Type: application/json

### Expert Approves Repairer
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/2/acceptRepairer
Content-Type: application/json

### Expert Disapproves Repairer
PATCH http://localhost:8080/occurrences/api/experts/expert2/occurrences/2/rejectRepairer
Content-Type: application/json

### Get All Repairers
GET http://localhost:8080/occurrences/api/repairers
Content-Type: application/json

### Repairer Starts Occurrence
PATCH http://localhost:8080/occurrences/api/repairers/repairer1/occurrences/2/start
Content-Type: application/json

### Repairer Fails Occurrence
PATCH http://localhost:8080/occurrences/api/repairers/repairer1/occurrences/2/fail
Content-Type: application/json

{
  "description": "Found a problem could not be fixed because..."
}

### Repairer Finishes Occurrence
PATCH http://localhost:8080/occurrences/api/repairers/repairer1/occurrences/1/finish
Content-Type: application/json

{
  "description": "Problem fixed and ready to be delivered"
}

### CLIENTS
### Create Client
POST http://localhost:8080/occurrences/api/clients
Content-Type: application/json

{
  "username": "pedro2",
  "email": "pedro@gmail.com",
  "name": "Pedro",
  "password": "123",
  "address": "Rua da Pedra n18",
  "phoneNumber": 915958652,
  "nif_nipc": 267503938
}

####LOGIN
### REQUEST JWT TOKEN
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "pedro",
  "password": "pedro1234"
}

####LOGIN ADMIN
### REQUEST JWT TOKEN
POST http://localhost:8080/occurrences/api/auth/login/admin
Content-Type: application/json
Accept: application/json

{
  "username": "admin1",
  "password": "123"
}

### Get Client Details
GET http://localhost:8080/occurrences/api/clients/client3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQzIiwiaWF0IjoxNjcyODcwNzg3LCJleHAiOjE2NzI4NzQzODd9.Gv4KufuxtoFWuYWViIP5hERnYaeldRqziqoqX07oHuU
Accept: application/json

### Update Client
PUT http://localhost:8080/occurrences/api/clients/pedro
//Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZWRybyIsImlhdCI6MTY3MjY3NDE5MCwiZXhwIjoxNjcyNjc3NzkwfQ.YgVeoucpbiJEuaDREWuPHQVXZfE9uKkJku2Ypnz53lQ
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "name": "LALA",
  "password": "pedro1234",
  "address": "Rua da Pedra n18",
  "phoneNumber": 915958652
}

### Delete Client
DELETE http://localhost:8080/occurrences/api/clients/pedro
//Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZWRybyIsImlhdCI6MTY3MjY3NDE5MCwiZXhwIjoxNjcyNjc3NzkwfQ.YgVeoucpbiJEuaDREWuPHQVXZfE9uKkJku2Ypnz53lQ
Content-Type: application/json

### Get Client Insurances
GET http://localhost:8080/occurrences/api/clients/pedro/insurances
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZWRybyIsImlhdCI6MTY3MjkzNDgwMSwiZXhwIjoxNjcyOTM4NDAxfQ.rkft7tI_pttC5HQuOElJeHAMWz8sewUYb6miIPgpsN4
Accept: application/json

### Get Expert Occurrences
GET http://localhost:8080/occurrences/api/experts/expert2/occurrences/assigned
Accept: application/json

### Get Administrator
GET http://localhost:8080/occurrences/api/administrators/admin1
Accept: application/json

### Get Insured Asset Type
GET http://localhost:8080/occurrences/api/insured-asset-type
Accept: application/json

###Client Send Email
POST http://localhost:8080/occurrences/api/clients/client2/email/send
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjcyOTE1NDM2LCJleHAiOjE2NzI5MTkwMzZ9.pF3kxBuD_lZSVuGYNOlxGLAjVMjVWlifTcMSNTbnK94
Content-Type: application/json

{
  "subject": "Bom dia",
  "message": "Bom dia. Compra Laranjas"
}

####LOGIN
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "expert2",
  "password": "exp"
}

###Expert Send Email
POST http://localhost:8080/occurrences/api/experts/expert2/email/send
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleHBlcnQyIiwiaWF0IjoxNjcyOTE2Nzg5LCJleHAiOjE2NzI5MjAzODl9.lgJUbMbo8SaExuwMokv6vDwJRGtbqA63t0qQT_En0DM
Content-Type: application/json

{
  "subject": "Bom dia",
  "message": "Bom dia. Compra melões"
}

####LOGIN
POST http://localhost:8080/occurrences/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "client2",
  "password": "123"
}

###Repairer Send Email
POST http://localhost:8080/occurrences/api/repairers/repairer1/email/send
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZXBhaXJlcjEiLCJpYXQiOjE2NzI5MTYxODAsImV4cCI6MTY3MjkxOTc4MH0.775skjEK_5of5ot-RXswgIND0XVNf0YtbFEirkhxHqA
Content-Type: application/json

{
  "subject": "Bom dia",
  "message": "Bom dia. Compra papaias"
}

###Update Password
PATCH http://localhost:8080/occurrences/api/clients/client2/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQyIiwiaWF0IjoxNjczMzYyMDI5LCJleHAiOjE2NzMzNjU2Mjl9.lhczuP6NiUeisJ_W4qk2J08oxJECeAlJkepqtSFICxo
Content-Type: application/json

{
  "password": "BomDiaaaaaa"
}
