###MOCKAPI
###Get All Policies from MockApi
GET https://63a9db1a594f75dc1dc27d9b.mockapi.io/insurances?code=FIDEL-1298302
Accept: application/json

###Get All Insurances from MockApi
GET http://localhost:8080/occurrences/api/mock/insurances
Accept: application/json

###Get All Insurance Companies from MockApi
GET http://localhost:8080/occurrences/api/mock/insuranceCompanies
Accept: application/json

###Get Insurance with specific code from MockApi
GET http://localhost:8080/occurrences/api/mock/insurances/code/FIDEL-1298302
Accept: application/json

###Get Insurance Company with specific code from MockApi
GET http://localhost:8080/occurrences/api/mock/insuranceCompanies/name/Fidelidade
Accept: application/json

###Get All repairers from a specific insurance company
GET http://localhost:8080/occurrences/api/mock/insuranceCompanies/name/Fidelidade/repairers
Accept: application/json